patch/1.19.3/ngx_stream_lua-missing-conf-in-init_worker.patch

See:
https://github.com/openresty/stream-lua-nginx-module/commit/a7193b14339e8c4cc5da024b7d86d0d20e0d2e9d
https://github.com/apache/apisix/issues/5125

feat: backport "some lua configurations were missing in the init_worker"

---

patch/1.19.9/ngx_lua-enable_keepalive.patch

fix: lua_newuserdata doesn't return aligned data in ARM64

---

.github/workflows/ci.yml

ci: setup asan

---

lib/resty/apisix/process.lua
patch/1.19.9/nginx-get_last_reopen_time.patch
t/process.t

feat: provide last reopen time so that we know if log file is reopened

---

lib/resty/apisix/request.lua
patch/1.19.9/ngx_lua-request_header_set.patch
src/ngx_http_apisix_module.c
src/ngx_http_apisix_module.h
t/request.t

feat: add mark for ngx.req.add/set_header

---

Makefile
lib/resty/apisix/stream/xrpc/socket.lua
t/stream/xrpc/downstream.t
t/stream/xrpc/upstream.t

feat: inherit methods from cosocket

---

lib/resty/apisix/stream/xrpc/socket.lua
patch/1.19.9/ngx_stream_lua-xrpc.patch
t/stream/xrpc/downstream.t
t/stream/xrpc/fuzzing.t
t/stream/xrpc/upstream.t

feat: add 'drain' method

---

patch/1.19.9/nginx-connection-original-dst.patch

Signed-off-by: Ling Samuel <lingsamuelgrace@gmail.com>
Add varaible `connection_original_dst` to support service mesh functionality.

feat: add variable connection_original_dst

---

lib/resty/apisix/stream/xrpc/socket.lua
patch/1.19.9/ngx_stream_lua-xrpc.patch
t/stream/xrpc/downstream.t

feat: add method to reset read buf

---

lib/resty/apisix/stream/xrpc/socket.lua
patch/1.19.9/ngx_stream_lua-xrpc.patch
t/stream/xrpc/downstream.t
t/stream/xrpc/fuzzing.t
t/stream/xrpc/upstream.t

feat: add read_line

---

lib/resty/apisix/patch.lua
patch/1.19.9/lua-resty-core-reject-in-handshake.patch
patch/1.19.9/ngx_lua-reject-in-handshake.patch
patch/1.19.9/ngx_stream_lua-reject-in-handshake.patch

feat: reject bad client TLS request in handshake

---

lib/resty/apisix/stream/xrpc/socket.lua
patch/1.19.9/ngx_stream_lua-xrpc.patch
t/stream/xrpc/misc.t

feat: add has_pending_data

---

.gitattributes

chore: correct linguist language

---

patch/1.21.4/nginx-grpc_set_header_authority.patch

feat: allow grpc_set_header to set :authority

---

patch/1.21.4/nginx-error_page_contains_apisix.patch

feat: let default error page contain APISIX

---

lib/resty/apisix/response.lua
patch/1.21.4/ngx_lua-skip_filter.patch
src/ngx_http_apisix_module.c
src/ngx_http_apisix_module.h
t/skip_filter.t

feat: allow skipping filters

---

.github/workflows/gm.yml

chore: remove `ls` which is only used to debug CI

---

patch/1.21.4/nginx-privileged_agent_process_thread.patch

feat: enable threads for privileged agent

---

patch/1.21.4/nginx-http2_per_iteration_stream_handling_limit.patch

copy from: https://mailman.nginx.org/pipermail/nginx-devel/2023-October/S36Q5HBXR7CAIMPLLPRSSSYR4PCMWILK.html

feat: add http2 per iteration stream handling limit patch

---

.github/workflows/ci.yml

close https://github.com/api7/apisix-nginx-module/issues/84

chore(ci): revert build-apisix-base.sh
